; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
lib_deps =
    https://github.com/SpacehuhnTech/SimpleCLI.git
    
[env:uno_r4_wifi_debug]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_type = debug
build_flags =
    -D LOGGING

[env:uno_r4_wifi_release]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
build_type = release

[env:master]
extends = uno_r4_wifi_release
build_flags = 
    -D MASTER_MODE

[env:client]
extends = uno_r4_wifi_release
build_flags = 
    -D CLIENT_MODE
